language: r

warnings_are_errors: true
sudo: required

r_binary_packages:
 - rentrez
 - XML
 - igraph
 - testthat
 - ggplot2
 - sys
r_github_packages:
 - jimhester/covr
 - hannesmuehleisen/MonetDBLite-R
 - ropensci/restez
 - AntonelliLab/outsider.base
 - AntonelliLab/outsider

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
on_failure: always